/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se.Prahlad;

//import java.awt.event.FocusEvent;

import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JOptionPane;

//import java.awt.event.FocusListener;

/**
 *
 * @author Knight_Leo10
 */
public class FileTasks extends javax.swing.JFrame {

    /**
     * Creates new form FileTasks
     */
    String nameco, namemo, namedel, namemu, namega, nameoth;
    String freqco, freqmo, freqdel, freqmu, freqga, freqoth;
    String timeco, timemo, timedel, timemu, timega, timeoth;
    String co, mo, del, mu, ga, oth;
    String textco, textco1, textmo, textmo1, textdel, textga, textmu, textoth;
    String coo, moo;
    
    public FileTasks() {
        initComponents();
        nameco="";
        namemo="";
        namedel="";
        namemu="";
        namega="";
        nameoth="";
        freqco="";
        freqmo="";
        freqdel="";
        freqmu="";
        freqga="";
        freqoth="";
        timeco="";
        timemo="";
        timedel="";
        timemu="";
        timega="";
        timeoth="";
        co="";
        mo="";
        del="";
        mu="";
        ga="";
        oth="";
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(960, 720));
        getContentPane().setLayout(null);

        jButton3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 255, 204));
        jButton3.setText("MOVE");
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 240, 130, 40);

        jButton4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 255, 204));
        jButton4.setText("DELETE");
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(30, 310, 130, 40);

        jButton5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(204, 255, 204));
        jButton5.setText("MUSIC");
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(30, 380, 120, 40);

        jButton6.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(204, 255, 204));
        jButton6.setText("GAMES");
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(30, 440, 130, 50);

        jButton10.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(204, 255, 204));
        jButton10.setText("BACK");
        jButton10.setContentAreaFilled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(640, 640, 130, 60);

        jTextField1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 153, 255));
        jTextField1.setToolTipText("Task Name");
        jTextField1.setHighlighter(null);
        jTextField1.setName(""); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(180, 170, 140, 50);

        jTextField2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(153, 153, 255));
        jTextField2.setToolTipText("ONCE/DAILY/WEEKLY");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(640, 170, 140, 50);

        jTextField3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(153, 153, 255));
        jTextField3.setToolTipText("ONCE/DAILY/WEEKLY");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(640, 230, 140, 60);

        jTextField4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(153, 153, 255));
        jTextField4.setToolTipText("Task Name");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(180, 230, 140, 60);

        jTextField5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(153, 153, 255));
        jTextField5.setToolTipText("enter path here");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(180, 300, 140, 60);

        jButton15.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButton15.setForeground(new java.awt.Color(204, 255, 204));
        jButton15.setText("EXIT");
        jButton15.setContentAreaFilled(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(800, 640, 130, 60);

        jButton17.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButton17.setForeground(new java.awt.Color(204, 255, 204));
        jButton17.setText("COPY");
        jButton17.setContentAreaFilled(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17);
        jButton17.setBounds(33, 173, 120, 40);

        jTextField8.setToolTipText("enter source path");
        getContentPane().add(jTextField8);
        jTextField8.setBounds(490, 170, 130, 40);

        jTextField13.setToolTipText("enter destination path");
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField13);
        jTextField13.setBounds(340, 170, 120, 50);

        jTextField14.setToolTipText("enter source");
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField14);
        jTextField14.setBounds(495, 240, 130, 40);

        jTextField7.setToolTipText("enter destination");
        getContentPane().add(jTextField7);
        jTextField7.setBounds(339, 240, 130, 40);

        jTextField15.setToolTipText("enter file name");
        getContentPane().add(jTextField15);
        jTextField15.setBounds(340, 310, 120, 40);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "txt", "sql", "html", "css", "php", "dll", "ini" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(490, 310, 130, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/se/Prahlad/FileTools.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 1090, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
       

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
 this.setVisible(false);
 new Home().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
this.setVisible(false);
 new Rating().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        try
        {
       String  nameco= jTextField1.getText();
       String freqco=jTextField2.getText();
      // String timeco=jSpinner7.getValue().toString()+":"+ jSpinner6.getValue().toString();
        String source = jTextField8.getText();
        String destination = jTextField13.getText();
        
        String source_first = String.valueOf(source.charAt(0));
    String dest_first = String.valueOf(destination.charAt(0));
    String c = "C";
    String d = "D";
    String e = "E";
    String f = "F";
    Path path = Paths.get(source);
   if(!((source_first.equals(c))||(source_first.equals(d))||(source_first.equals(e))||(source_first.equals(f))))
   {
       JOptionPane.showMessageDialog(null,"Wrong source path","Source Error",JOptionPane.ERROR_MESSAGE);
   }
   if(!((dest_first.equals(c))||(dest_first.equals(d))||(dest_first.equals(e))||(dest_first.equals(f))))
   {
       JOptionPane.showMessageDialog(null,"Wrong destination path","Destination Error",JOptionPane.ERROR_MESSAGE);
   }
   char s1 = source.charAt(1);
   char s2 = source.charAt(2);
   char s3 = destination.charAt(1);
   char s4 = destination.charAt(2);
    if((s1 != 58)||(s3!=58)||(s2!=92)||(s4!=92))
        {
          JOptionPane.showMessageDialog(null,"Please check the syntax","Syntax Error",JOptionPane.ERROR_MESSAGE);  
        }
    else if(source.equals(destination))
    {
        JOptionPane.showMessageDialog(null,"The file(s) cannot be copied onto itself","Error",JOptionPane.ERROR_MESSAGE);
    }
    else if (Files.notExists(path)) {
  JOptionPane.showMessageDialog(null,"The file(s) does not exist");
}
   else if(((source_first.equals(c))||(source_first.equals(d))||(source_first.equals(e))||(source_first.equals(f))) &&
            ((dest_first.equals(c))||(dest_first.equals(d))||(dest_first.equals(e))||(dest_first.equals(f))))
            
    {  
    String sub1 = source.substring(0,2);
    String sub2 = source.substring(3);
    String sub3 = destination.substring(0,2);
    String sub4 = destination.substring(3);
    String s = "cmd /c copy "+sub1+"\\"+sub2+"\\* "+sub3+"\\"+sub4;
    Process p=Runtime.getRuntime().exec(s); 
    //Process p=Runtime.getRuntime().exec("cmd /c copy F:\\Shoebee\\* F:\\Shoebee1");
    p.waitFor();
    BufferedReader reader=new BufferedReader(new InputStreamReader(p.getInputStream())); 
    String line=reader.readLine(); 
    while(line!=null) 
        { 
            System.out.println(line); 
            line=reader.readLine(); 
        } 
    JOptionPane.showMessageDialog(null,"Files copied sucessfully");
    }
    else
    {
         JOptionPane.showMessageDialog(null,"could not copy");
    }

        }
         catch(StringIndexOutOfBoundsException f)
         {
             JOptionPane.showMessageDialog(null,"Field empty,","Error",JOptionPane.ERROR_MESSAGE);
         }
catch(  IOException | InterruptedException e1) {}   
                            
                                    
        

    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try
        {
        namemo=jTextField4.getText();
        freqmo=jTextField3.getText();
        //timemo=jSpinner8.getValue().toString()+":"+ jSpinner1.getValue().toString();
        
        String source = jTextField14.getText();
    String destination = jTextField7.getText();
    String source_first = String.valueOf(source.charAt(0));
    String dest_first = String.valueOf(destination.charAt(0));
    String c = "C";
    String d = "D";
    String e = "E";
    String f = "F";
   if(!((source_first.equals(c))||(source_first.equals(d))||(source_first.equals(e))||(source_first.equals(f))))
   {
       JOptionPane.showMessageDialog(null,"Wrong source path","Source Error",JOptionPane.ERROR_MESSAGE);
   }
   if(!((dest_first.equals(c))||(dest_first.equals(d))||(dest_first.equals(e))||(dest_first.equals(f))))
   {
       JOptionPane.showMessageDialog(null,"Wrong destination path","Destination Error",JOptionPane.ERROR_MESSAGE);
   }
   char s1 = source.charAt(1);
   char s2 = source.charAt(2);
   char s3 = destination.charAt(1);
   char s4 = destination.charAt(2);
   
Path path = Paths.get(source);
    if((s1 != 58)||(s3!=58)||(s2!=92)||(s4!=92))
        {
          JOptionPane.showMessageDialog(null,"Please check the syntax","Syntax Error",JOptionPane.ERROR_MESSAGE);  
        }
      else if (Files.notExists(path)) {
  JOptionPane.showMessageDialog(null,"The file(s) does not exist");
}
    
    else if(((source_first.equals(c))||(source_first.equals(d))||(source_first.equals(e))||(source_first.equals(f))) &&
            ((dest_first.equals(c))||(dest_first.equals(d))||(dest_first.equals(e))||(dest_first.equals(f))))
            
    {
    String sub1 = source.substring(0,2);
    String sub2 = source.substring(3);
    String sub3 = destination.substring(0,2);
    String sub4 = destination.substring(3);
    String s = "cmd /c move "+sub1+"\\"+sub2+"\\* "+sub3+"\\"+sub4;
    Process p=Runtime.getRuntime().exec(s); 
    //Process p=Runtime.getRuntime().exec("cmd /c copy F:\\Shoebee\\* F:\\Shoebee1");
    p.waitFor();
    BufferedReader reader=new BufferedReader(new InputStreamReader(p.getInputStream())); 
    String line=reader.readLine(); 
    while(line!=null) 
        { 
            System.out.println(line); 
            line=reader.readLine(); 
        } 
    JOptionPane.showMessageDialog(null,"Files moved sucessfully");
    }
    else
    {
         JOptionPane.showMessageDialog(null,"could not move");
    }


} 
         catch(StringIndexOutOfBoundsException f)
         {
             JOptionPane.showMessageDialog(null,"Field empty,","Error",JOptionPane.ERROR_MESSAGE);
         }
catch(  IOException | InterruptedException e1) {}   
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try 
{ 
    
    String source = jTextField5.getText();
    

    String source_first = String.valueOf(source.charAt(0));
   
    String c = "C";
    String d = "D";
    String e = "E";
    String f = "F";
    String name = jTextField15.getText();
    String ext = (String)jList1.getSelectedValue();
    String s = "cmd /c del "+source+"\\"+name+"."+ext;
    String ss = source+"\\"+name+"."+ext;
    File fu = new File(ss); 
 
   if(!((source_first.equals(c))||(source_first.equals(d))||(source_first.equals(e))||(source_first.equals(f))))
   {
       JOptionPane.showMessageDialog(null,"Wrong source path","Source Error",JOptionPane.ERROR_MESSAGE);
   }
   else if(jList1.getSelectedIndex()==-1)
       {
           JOptionPane.showMessageDialog(null,"please select file extension");
       }
   
   else if(!(fu.exists())){
		  JOptionPane.showMessageDialog(null,"File does not exist");
          }
 
   
   else if(((source_first.equals(c))||(source_first.equals(d))||(source_first.equals(e))||(source_first.equals(f))))
            
    {
    
    Process p=Runtime.getRuntime().exec(s); 
    p.waitFor();
    BufferedReader reader=new BufferedReader(new InputStreamReader(p.getInputStream())); 
    String line=reader.readLine(); 
    while(line!=null) 
        { 
            System.out.println(line); 
            line=reader.readLine(); 
        } 
    JOptionPane.showMessageDialog(null,"File deleted sucessfully");
    }
  
    else
    {
         JOptionPane.showMessageDialog(null,"could not delete");
    }
    }                                        
catch(StringIndexOutOfBoundsException f)
         {
             JOptionPane.showMessageDialog(null,"Field empty,","Error",JOptionPane.ERROR_MESSAGE);
         }
    catch(  IOException | InterruptedException e1) {}         // TODO add your handling code here:
       
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
      Desktop desktop = Desktop.getDesktop();
      
        try {
            File dirToOpen = new File("C:\\Users\\Mahe\\Music\\songs\\hindi");
            desktop.open(dirToOpen);
        } 
        catch (Exception iae) {
            System.out.println("File Not Found");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FileTasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FileTasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FileTasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileTasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FileTasks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
